# Auto-generated by msdevopsagent on release — do not edit by hand.
class Q01sdkQa < Formula
  desc "Q01 Platform SDK CLI"
  homepage "https://app-qa.q01.io"
  version "1.0.66"

  on_macos do
    on_arm do
      url "https://app-qa.q01.io/api/v4/q01sdk/download/?file=macarm.tar.gz&version=1.0.66"
      sha256 "<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/app/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    
    <title>
      q01 Platform
    </title>
    <script type="module" crossorigin src="/app/assets/index-f23fe82f.js"></script>
    <link rel="stylesheet" href="/app/assets/style-37efb64a.css">
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    
    <!--
      This HTML file is a template.
      If you open it directly in the browser, you will see an empty page.

      You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the <body> tag.

      To begin the development, run `npm dev` or `yarn start`.
      To create a production bundle, use `npm run build` or `yarn build`.
    -->
  </body>
</html>"
    end

    on_intel do
      url "https://app-qa.q01.io/api/v4/q01sdk/download/?file=mac.tar.gz&version=1.0.66"
      sha256 "<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/app/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    
    <title>
      q01 Platform
    </title>
    <script type="module" crossorigin src="/app/assets/index-f23fe82f.js"></script>
    <link rel="stylesheet" href="/app/assets/style-37efb64a.css">
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    
    <!--
      This HTML file is a template.
      If you open it directly in the browser, you will see an empty page.

      You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the <body> tag.

      To begin the development, run `npm dev` or `yarn start`.
      To create a production bundle, use `npm run build` or `yarn build`.
    -->
  </body>
</html>"
    end
  end

  on_linux do
    on_arm do
      url "https://app-qa.q01.io/api/v4/q01sdk/download/?file=lin.tar.gz&version=1.0.66"
      sha256 "<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/app/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    
    <title>
      q01 Platform
    </title>
    <script type="module" crossorigin src="/app/assets/index-f23fe82f.js"></script>
    <link rel="stylesheet" href="/app/assets/style-37efb64a.css">
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    
    <!--
      This HTML file is a template.
      If you open it directly in the browser, you will see an empty page.

      You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the <body> tag.

      To begin the development, run `npm dev` or `yarn start`.
      To create a production bundle, use `npm run build` or `yarn build`.
    -->
  </body>
</html>"
    end

    on_intel do
      url "https://app-qa.q01.io/api/v4/q01sdk/download/?file=lin.tar.gz&version=1.0.66"
      sha256 "<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/app/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    
    <title>
      q01 Platform
    </title>
    <script type="module" crossorigin src="/app/assets/index-f23fe82f.js"></script>
    <link rel="stylesheet" href="/app/assets/style-37efb64a.css">
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    
    <!--
      This HTML file is a template.
      If you open it directly in the browser, you will see an empty page.

      You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the <body> tag.

      To begin the development, run `npm dev` or `yarn start`.
      To create a production bundle, use `npm run build` or `yarn build`.
    -->
  </body>
</html>"
    end
  end

  def install
    bin.install "q01sdk" => "q01sdk-qa"
    config_dir = Pathname.new(Dir.home) / ".q01sdk"
    config_dir.mkpath
    env_file = config_dir / ".env"
    env_file.write("Host=\"https://app-qa.q01.io\"\nEnv=\"qa\"\nDEVTOOL=devspace\n")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/q01sdk-qa --version")
  end
end
