# Auto-generated by msdevopsagent on release — do not edit by hand.
class Q01sdk < Formula
  desc "Q01 Platform SDK CLI"
  homepage "https://app.q01.io"
  version "1.0.76"

  on_macos do
    on_arm do
      url "https://sdk.q01.io/q01sdk/prod/#{version}/q01sdk-darwin-arm64.tar.gz"
      sha256 "883d9e57cae7bb67817414763b354056a89adfc0ccc955ccd0e39e3a2e25984a"
    end

    on_intel do
      url "https://sdk.q01.io/q01sdk/prod/#{version}/q01sdk-darwin-amd64.tar.gz"
      sha256 "b8ec3b639826371d0a831647291a4a602af24862cef46ce60b481c7eebf6211b"
    end
  end

  on_linux do
    # NOTE: no linux-arm64 build target yet — arm falls back to the amd64 binary.
    on_arm do
      url "https://sdk.q01.io/q01sdk/prod/#{version}/q01sdk-linux-amd64.tar.gz"
      sha256 "aacf91aea4ea12dcbe1e4994c6e683a35b23604a557bf8d2c14fac37edcdc7ef"
    end

    on_intel do
      url "https://sdk.q01.io/q01sdk/prod/#{version}/q01sdk-linux-amd64.tar.gz"
      sha256 "aacf91aea4ea12dcbe1e4994c6e683a35b23604a557bf8d2c14fac37edcdc7ef"
    end
  end

  def install
    bin.install "q01sdk"
    config_dir = Pathname.new(Dir.home) / ".q01sdk"
    config_dir.mkpath
    env_file = config_dir / ".env"
    env_file.write("DEVTOOL=devspace\n")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/q01sdk --version")
  end
end
