# Auto-generated by msdevopsagent on release — do not edit by hand.
class Q01sdkQa < Formula
  desc "Q01 Platform SDK CLI"
  homepage "https://app-qa.q01.io"
  version "1.0.72"

  on_macos do
    on_arm do
      url "https://sdk.q01.io/q01sdk/qa/q01sdk-darwin-arm64.tar.gz"
      sha256 "7c2937fbc1f5ce97375a3278c1049d6b0e5e5ccc3180c71dcd80dc25b6b36dff"
    end

    on_intel do
      url "https://sdk.q01.io/q01sdk/qa/q01sdk-darwin-amd64.tar.gz"
      sha256 "beecbcdcf1fcb4fb634f7fe76107ad55e012222395641cba5c452223af154318"
    end
  end

  on_linux do
    on_arm do
      url "https://sdk.q01.io/q01sdk/qa/q01sdk-linux-amd64.tar.gz"
      sha256 "f48eb0e40928a4b0bb5d72d5e41f1a52f29671250139405af5785138d4aff649"
    end

    on_intel do
      url "https://sdk.q01.io/q01sdk/qa/q01sdk-linux-amd64.tar.gz"
      sha256 "f48eb0e40928a4b0bb5d72d5e41f1a52f29671250139405af5785138d4aff649"
    end
  end

  def install
    bin.install "q01sdk" => "q01sdk-qa"
    config_dir = Pathname.new(Dir.home) / ".q01sdk"
    config_dir.mkpath
    env_file = config_dir / ".env"
    env_file.write("Host=\"https://app-qa.q01.io\"\nEnv=\"qa\"\nDEVTOOL=devspace\n")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/q01sdk-qa --version")
  end
end
