# Auto-generated by msdevopsagent on release — do not edit by hand.
class Q01sdk < Formula
  desc "Q01 Platform SDK CLI"
  homepage "https://app.q01.io"
  version "1.0.81"

  on_macos do
    on_arm do
      url "https://sdk.q01.io/q01sdk/prod/#{version}/q01sdk-darwin-arm64.tar.gz"
      sha256 "0f9ebdf72420f2db76ee62cf4ffd2abadebd885cd1533516edacf40d74d3af48"
    end

    on_intel do
      url "https://sdk.q01.io/q01sdk/prod/#{version}/q01sdk-darwin-amd64.tar.gz"
      sha256 "a6751cdf3a93b73d4e7616b80bbf9b19961488b6e8615bf8929dc21127a2f18e"
    end
  end

  on_linux do
    # NOTE: no linux-arm64 build target yet — arm falls back to the amd64 binary.
    on_arm do
      url "https://sdk.q01.io/q01sdk/prod/#{version}/q01sdk-linux-amd64.tar.gz"
      sha256 "0e4f57d00ae03e7dbb430bbc5f61b832730329706bbd8730b8c58b4f0798f5cc"
    end

    on_intel do
      url "https://sdk.q01.io/q01sdk/prod/#{version}/q01sdk-linux-amd64.tar.gz"
      sha256 "0e4f57d00ae03e7dbb430bbc5f61b832730329706bbd8730b8c58b4f0798f5cc"
    end
  end

  def install
    bin.install "q01sdk"
    config_dir = Pathname.new(Dir.home) / ".q01sdk"
    config_dir.mkpath
    env_file = config_dir / ".env"
    env_file.write("DEVTOOL=devspace\n")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/q01sdk --version")
  end
end
