# Auto-generated by msdevopsagent on release — do not edit by hand.
class Q01sdk < Formula
  desc "Q01 Platform SDK CLI"
  homepage "https://app.q01.io"
  version "1.0.67"

  on_macos do
    on_arm do
      url "https://app.q01.io/api/v4/q01sdk/download/?file=macarm.tar.gz&version=1.0.67"
      sha256 "44b63c3abb5f564e8f28c2da05e275f4b4e54d67253706cb7e1423ef1d4c8bd9"
    end

    on_intel do
      url "https://app.q01.io/api/v4/q01sdk/download/?file=mac.tar.gz&version=1.0.67"
      sha256 "cb73403dfebcc6acfa04ba5530186728351d1ca5171ed561f063fdb09be50e27"
    end
  end

  on_linux do
    on_arm do
      url "https://app.q01.io/api/v4/q01sdk/download/?file=lin.tar.gz&version=1.0.67"
      sha256 "20a5eee356ef31ff0fb796acabab73bfc8a396f1f588cf0430ae1118aa3d511d"
    end

    on_intel do
      url "https://app.q01.io/api/v4/q01sdk/download/?file=lin.tar.gz&version=1.0.67"
      sha256 "20a5eee356ef31ff0fb796acabab73bfc8a396f1f588cf0430ae1118aa3d511d"
    end
  end

  def install
    bin.install "q01sdk"
    config_dir = Pathname.new(Dir.home) / ".q01sdk"
    config_dir.mkpath
    env_file = config_dir / ".env"
    env_file.write("")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/q01sdk --version")
  end
end
