# Auto-generated by msdevopsagent on release — do not edit by hand.
class Q01sdkInt < Formula
  desc "Q01 Platform SDK CLI"
  homepage "https://app-int.q01.io"
  version "1.0.86"

  on_macos do
    on_arm do
      url "https://sdk.q01.io/q01sdk/int/#{version}/q01sdk-darwin-arm64.tar.gz"
      sha256 "0f2a17d41e6d7c9fa5332d30189c2200ad2f4b764900ed49c159131f50b61c6f"
    end

    on_intel do
      url "https://sdk.q01.io/q01sdk/int/#{version}/q01sdk-darwin-amd64.tar.gz"
      sha256 "eb4fc58643db27666c25cb11f8fb50bc3665c38c1ad42810fda263c9b149e094"
    end
  end

  on_linux do
    # NOTE: no linux-arm64 build target yet — arm falls back to the amd64 binary.
    on_arm do
      url "https://sdk.q01.io/q01sdk/int/#{version}/q01sdk-linux-amd64.tar.gz"
      sha256 "731c0a09327c6d8f6c22fc088a1be4f946443f844c367fe81d91d8251fe172b0"
    end

    on_intel do
      url "https://sdk.q01.io/q01sdk/int/#{version}/q01sdk-linux-amd64.tar.gz"
      sha256 "731c0a09327c6d8f6c22fc088a1be4f946443f844c367fe81d91d8251fe172b0"
    end
  end

  def install
    bin.install "q01sdk" => "q01sdk-int"
    config_dir = Pathname.new(Dir.home) / ".q01sdk"
    config_dir.mkpath
    env_file = config_dir / ".env"
    env_file.write("Host=\"https://app-int.q01.io\"\nEnv=\"int\"\nDEVTOOL=devspace\n")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/q01sdk-int --version")
  end
end
